
export const notifications = [
    {
      id: 1,
      name: "Tania send you a message",
      time: "13 minutes ago",
      description: "A list of new leads has been added to your dashboard",
      avatar: "/icons/notification1.png",
    },
    {
      id: 2,
      name: "Natali replied to your email.",
      time: "1 hour ago",
      description: "A list of new leads has been added to your dashboard",
      avatar: "/icons/notification2.png",
    },
    {
      id: 3,
      name: "You've received a payment.",
      time: "5 hours ago",
      description: "A list of new leads has been added to your dashboard",
      avatar: "/icons/notification1.png",
    },
    {
      id: 4,
      name: "You've received a payment.",
      time: "6 hours ago",
      description: "A list of new leads has been added to your dashboard",
      avatar: "/icons/notification1.png",
    },
    {
      id: 5,
      name: "You've received a payment.",
      time: "8 hours ago",
      description: "A list of new leads has been added to your dashboard",
      avatar: "/icons/notification2.png",
    },
  ];

  export const callData = [
    {
      name: "Krishna Rajput",
      summary: "In 2nd year, Wants to purchase DSA course",
      lead: "Hot",
      lsa: "Very Positive",
      recommendation: "Ask how was the demo and how was the experience",
      lastDateTime: "24 Dec 2024 | 1:21 PM",
    },
    {
      name: 'Narayan Tripathi',
      summary: 'Clicked on the Advertisement',
      lead: 'New Lead',
      lsa: 'Positive',
      recommendation: 'Confirmation to come next time',
      lastDateTime: '24 Dec 2024 | 1:21 PM',
    },
    {
      name: 'Krishna Rajput',
      summary: 'In 2nd year, Wants to purchase DSA course',
      lead: 'Warm',
      lsa: 'Very Positive',
      recommendation: 'Ask how was the demo and how was the experience',
      lastDateTime: '24 Dec 2024 | 1:21 PM',
    },
    {
      name: "Krishna Rajput",
      summary: "In 2nd year, Wants to purchase DSA course",
      lead: "Hot",
      lsa: "Very Positive",
      recommendation: "Ask how was the demo and how was the experience",
      lastDateTime: "24 Dec 2024 | 1:21 PM",
    },
    {
      name: "Krishna Rajput",
      summary: "In 2nd year, Wants to purchase DSA course",
      lead: "Hot",
      lsa: "Very Positive",
      recommendation: "Ask how was the demo and how was the experience",
      lastDateTime: "24 Dec 2024 | 1:21 PM",
    },
    {
      name: "Krishna Rajput",
      summary: "In 2nd year, Wants to purchase DSA course",
      lead: "Hot",
      lsa: "Very Positive",
      recommendation: "Ask how was the demo and how was the experience",
      lastDateTime: "24 Dec 2024 | 1:21 PM",
    },
    {
      name: "Krishna Rajput",
      summary: "In 2nd year, Wants to purchase DSA course",
      lead: "Hot",
      lsa: "Very Positive",
      recommendation: "Ask how was the demo and how was the experience",
      lastDateTime: "24 Dec 2024 | 1:21 PM",
    },
    {
      name: "Krishna Rajput",
      summary: "In 2nd year, Wants to purchase DSA course",
      lead: "Hot",
      lsa: "Very Positive",
      recommendation: "Ask how was the demo and how was the experience",
      lastDateTime: "24 Dec 2024 | 1:21 PM",
    },
    // Add more data as needed
  ];

  export const messageData = [
    {
      name: "John Doe",
      summary: "Asked about refund policy",
      lead: "Cold",
      lsa: "Neutral",
      recommendation: "Send details about refund process",
      lastDateTime: "23 Dec 2024 | 3:45 PM",
    },
    {
      name: "Jane Smith",
      summary: "Interested in upcoming offers",
      lead: "Warm",
      lsa: "Positive",
      recommendation: "Follow up next week",
      lastDateTime: "22 Dec 2024 | 12:30 PM",
    },
    {
      name: "John Doe",
      summary: "Asked about refund policy",
      lead: "Cold",
      lsa: "Neutral",
      recommendation: "Send details about refund process",
      lastDateTime: "23 Dec 2024 | 3:45 PM",
    },
    {
      name: "Jane Smith",
      summary: "Interested in upcoming offers",
      lead: "Warm",
      lsa: "Positive",
      recommendation: "Follow up next week",
      lastDateTime: "22 Dec 2024 | 12:30 PM",
    },
    {
      name: "Jane Smith",
      summary: "Interested in upcoming offers",
      lead: "Warm",
      lsa: "Positive",
      recommendation: "Follow up next week",
      lastDateTime: "22 Dec 2024 | 12:30 PM",
    },
    {
      name: "Jane Smith",
      summary: "Interested in upcoming offers",
      lead: "Warm",
      lsa: "Positive",
      recommendation: "Follow up next week",
      lastDateTime: "22 Dec 2024 | 12:30 PM",
    },
    {
      name: "Jane Smith",
      summary: "Interested in upcoming offers",
      lead: "Warm",
      lsa: "Positive",
      recommendation: "Follow up next week",
      lastDateTime: "22 Dec 2024 | 12:30 PM",
    },
    {
      name: "Jane Smith",
      summary: "Interested in upcoming offers",
      lead: "Warm",
      lsa: "Positive",
      recommendation: "Follow up next week",
      lastDateTime: "22 Dec 2024 | 12:30 PM",
    },
    {
      name: "Jane Smith",
      summary: "Interested in upcoming offers",
      lead: "Warm",
      lsa: "Positive",
      recommendation: "Follow up next week",
      lastDateTime: "22 Dec 2024 | 12:30 PM",
    },
    // Add more data as needed
  ];

  export const tableHeadings = [
    "Call ID",
    "Duration",
    "Type & Reason",
    "Source",
    "Sentiment",
    "Lead",
    "Next Action",
    "Date & Time",
    "Action",
  ];

  export const tableData = [
    {
      "Call ID": "B1264h4826-ajojbksjdbs",
      Duration: "17 m 52 s",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Call ID": "9127832477-ksddajkasd",
      Duration: "7 m 28 s",
      "Type & Reason": "Confirmation reschedule of the Demo",
      Source: "",
      Sentiment: "Positive",
      Lead: "Cold",
      "Next Action": "Confirmation to come next time",
      "Date & Time": "12 Nov 2024 | 2:22 PM",
      Action: "...",
    },
    {
      "Call ID": "9328828823-ajcjbjskdb",
      Duration: "13 m 23 s",
      "Type & Reason": "Remind about the payment of the product purchased",
      Source: "",
      Sentiment: "Neutral",
      Lead: "Warm",
      "Next Action": "Thanks for the purchase and ask Feedback",
      "Date & Time": "21 Oct 2024 | 3:42 PM",
      Action: "...",
    },
    {
      "Call ID": "81264h4826-ajojbksjdbs",
      Duration: "11 m 12 s",
      "Type & Reason": "Persuade to purchase the product",
      Source: "",
      Sentiment: "Negative",
      Lead: "Closed",
      "Next Action": "No action required, customer denied",
      "Date & Time": "10 Oct 2024 | 1:42 PM",
      Action: "...",
    },
    {
      "Call ID": "B1264h4826-ajojbksjdbs",
      Duration: "17 m 52 s",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Call ID": "B1264h4826-ajojbksjdbs",
      Duration: "17 m 52 s",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Call ID": "B1264h4826-ajojbksjdbs",
      Duration: "17 m 52 s",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Call ID": "B1264h4826-ajojbksjdbs",
      Duration: "17 m 52 s",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
  ];

  export const tableHeadings2 = [
    "Chat ID",
    "Counter",
    "Type & Reason",
    "Source",
    "Sentiment",
    "Lead",
    "Next Action",
    "Date & Time",
    "Action",
  ];

  export const tableData2 = [
    {
      "Chat ID": "B1264h4826-ajojbksjdbs",
      Counter: "17 ",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Chat ID": "9127832477-ksddajkasd",
      Counter: "37 ",
      "Type & Reason": "Confirmation reschedule of the Demo",
      Source: "",
      Sentiment: "Positive",
      Lead: "Cold",
      "Next Action": "Confirmation to come next time",
      "Date & Time": "12 Nov 2024 | 2:22 PM",
      Action: "...",
    },
    {
      "Chat ID": "9328828823-ajcjbjskdb",
      Counter: "13 ",
      "Type & Reason": "Remind about the payment of the product purchased",
      Source: "",
      Sentiment: "Neutral",
      Lead: "Warm",
      "Next Action": "Thanks for the purchase and ask Feedback",
      "Date & Time": "21 Oct 2024 | 3:42 PM",
      Action: "...",
    },
    {
      "Chat ID": "81264h4826-ajojbksjdbs",
      Counter: "11 ",
      "Type & Reason": "Persuade to purchase the product",
      Source: "",
      Sentiment: "Negative",
      Lead: "Closed",
      "Next Action": "No action required, customer denied",
      "Date & Time": "10 Oct 2024 | 1:42 PM",
      Action: "...",
    },
    {
      "Chat ID": "B1264h4826-ajojbksjdbs",
      Counter: "17 ",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Chat ID": "B1264h4826-ajojbksjdbs",
      Counter: "17 ",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Chat ID": "B1264h4826-ajojbksjdbs",
      Counter: "27 ",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
    {
      "Chat ID": "B1264h4826-ajojbksjdbs",
      Counter: "23",
      "Type & Reason": "Confirmation for attending the demo",
      Source: "",
      Sentiment: "Very Positive",
      Lead: "Hot",
      "Next Action": "Ask how was the demo and how was the experience",
      "Date & Time": "24 Dec 2024 | 1:21 PM",
      Action: "...",
    },
  ]



  export const CData = [
    { day: "Sun", revenue: 30 },
    { day: "Mon", revenue: 60 },
    { day: "Tue", revenue: 25 },
    { day: "Wed", revenue: 60 },
    { day: "Thu", revenue: 20 },
    { day: "Fri", revenue: 40 },
    { day: "Sat", revenue: 15 },
  ];



  export const visitorData = [{
    // Add your visitor data here
    count: 1235,
    trend: "down" ,
    description: "Leads Procured",
    color: "green",
    chartData: [10, 0, 20, 10, 40],
  },
  {
    count: 456,
    trend: "up",
    description: "Leads Converted",
    color: "red",
    chartData: [30, 25, 35, 20, 40],
  }];
